export interface CityData {
  slug: string;
  name: string;
  state: string;
  population: string;
  avOperators: string[];
  droneOperators: string[];
  tier: 1 | 2 | 3;
  avActivity: "active" | "pilot" | "planning";
  accentColor: string;
  description: string;
}

export const CITIES: CityData[] = [
  // ── TIER 1 ────────────────────────────────────────────────────────────────
  {
    slug: "san-francisco",
    name: "San Francisco",
    state: "CA",
    population: "873,965",
    avOperators: ["Waymo", "Zoox", "Cruise"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 1,
    avActivity: "active",
    accentColor: "#00d4ff",
    description: "The most active AV market in America, with over 100,000 weekly Waymo rides and multiple operators expanding commercial service.",
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    state: "CA",
    population: "3,898,747",
    avOperators: ["Waymo", "Zoox"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 1,
    avActivity: "active",
    accentColor: "#7b2fff",
    description: "The nation's largest AV expansion market. Waymo launched LA operations in 2024 with rapid growth across the metro.",
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    state: "AZ",
    population: "1,608,139",
    avOperators: ["Waymo", "Cruise", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 1,
    avActivity: "active",
    accentColor: "#ff9a00",
    description: "America's first commercially active fully autonomous ride-hail city. Waymo has operated driverless vehicles in Phoenix since 2020.",
  },
  {
    slug: "austin",
    name: "Austin",
    state: "TX",
    population: "961,855",
    avOperators: ["Waymo", "May Mobility", "Nuro"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 1,
    avActivity: "active",
    accentColor: "#00ff88",
    description: "A major AV testing and commercial deployment hub. Austin's density and tech-forward culture make it an ideal early market.",
  },
  {
    slug: "new-york",
    name: "New York",
    state: "NY",
    population: "8,336,817",
    avOperators: ["Waymo", "Zoox", "Aurora"],
    droneOperators: ["Zipline", "Amazon Prime Air"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "The largest US metro entering AV commercial pilot phases. Complexity and density create unique curb infrastructure challenges.",
  },
  {
    slug: "chicago",
    name: "Chicago",
    state: "IL",
    population: "2,696,555",
    avOperators: ["May Mobility", "Motional"],
    droneOperators: ["Wing"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#0066ff",
    description: "Active AV pilot programs with May Mobility operating fixed-route autonomy and Motional expanding commercial service.",
  },
  {
    slug: "seattle",
    name: "Seattle",
    state: "WA",
    population: "749,256",
    avOperators: ["Waymo", "Zoox", "Aurora"],
    droneOperators: ["Amazon Prime Air", "Wing"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Amazon's home city is a major drone delivery market. Aurora and Waymo are expanding Seattle AV operations.",
  },
  {
    slug: "miami",
    name: "Miami",
    state: "FL",
    population: "442,241",
    avOperators: ["Waymo", "Motional"],
    droneOperators: ["Wing", "Zipline"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#7b2fff",
    description: "Florida's warm climate and tourism economy make Miami a priority AV deployment market.",
  },
  {
    slug: "washington-dc",
    name: "Washington DC",
    state: "DC",
    population: "689,545",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Zipline", "Wing"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Federal city with active AV pilots and growing policy framework supporting autonomous infrastructure deployment.",
  },
  {
    slug: "boston",
    name: "Boston",
    state: "MA",
    population: "675,647",
    avOperators: ["Motional", "Zoox"],
    droneOperators: ["Zipline"],
    tier: 1,
    avActivity: "pilot",
    accentColor: "#ff9a00",
    description: "A major robotics and AV research hub with MIT and Harvard driving commercial partnership deployments.",
  },

  // ── TIER 2 ────────────────────────────────────────────────────────────────
  {
    slug: "denver",
    name: "Denver",
    state: "CO",
    population: "715,522",
    avOperators: ["May Mobility", "Waymo"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "Growing AV deployment market with May Mobility fixed-route operations and Waymo expansion planning.",
  },
  {
    slug: "dallas",
    name: "Dallas",
    state: "TX",
    population: "1,304,379",
    avOperators: ["Nuro", "Aurora"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#7b2fff",
    description: "Major logistics hub with Nuro expanding delivery operations and Aurora Highway piloting commercial freight.",
  },
  {
    slug: "houston",
    name: "Houston",
    state: "TX",
    population: "2,304,580",
    avOperators: ["Nuro", "Aurora", "May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#ff9a00",
    description: "America's energy capital is investing in smart infrastructure with multiple AV operators in active pilot programs.",
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    state: "GA",
    population: "498,715",
    avOperators: ["May Mobility", "Waymo"],
    droneOperators: ["Zipline", "Wing"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Major Southeast hub for AV and drone deployment. Hartsfield-Jackson Airport creates significant autonomous infrastructure demand.",
  },
  {
    slug: "nashville",
    name: "Nashville",
    state: "TN",
    population: "689,447",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "planning",
    accentColor: "#ffd700",
    description: "Rapidly growing Sunbelt city actively planning autonomous infrastructure to manage population growth.",
  },
  {
    slug: "san-diego",
    name: "San Diego",
    state: "CA",
    population: "1,386,932",
    avOperators: ["Waymo", "Zoox"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Southern California's second-largest city with active Waymo pilots and proximity to major military and research institutions.",
  },
  {
    slug: "las-vegas",
    name: "Las Vegas",
    state: "NV",
    population: "641,903",
    avOperators: ["Zoox", "May Mobility", "Navya"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "active",
    accentColor: "#ff9a00",
    description: "Major AV testing ground with the Strip requiring intense curb management. Zoox operates commercial AV service.",
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    state: "MN",
    population: "429,606",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#0066ff",
    description: "Cold-weather AV testing leader. May Mobility fixed-route operations prove AV viability in winter conditions.",
  },
  {
    slug: "portland",
    name: "Portland",
    state: "OR",
    population: "652,503",
    avOperators: ["Waymo", "Nuro"],
    droneOperators: ["Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "Progressive transportation policy and tech industry presence drive AV adoption in Oregon's largest city.",
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh",
    state: "PA",
    population: "302,971",
    avOperators: ["Aurora", "Waymo"],
    droneOperators: ["Zipline"],
    tier: 2,
    avActivity: "active",
    accentColor: "#7b2fff",
    description: "Historic AV testing city. Aurora Highway and Waymo maintain active operations. Carnegie Mellon University drives research.",
  },
  {
    slug: "san-jose",
    name: "San Jose",
    state: "CA",
    population: "1,013,240",
    avOperators: ["Waymo", "Zoox"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Silicon Valley's largest city with deep ties to AV technology companies and active pilot operations expanding from SF Bay Area.",
  },
  {
    slug: "raleigh",
    name: "Raleigh",
    state: "NC",
    population: "467,665",
    avOperators: ["May Mobility", "Waymo"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "Research Triangle's capital city leading the Southeast in autonomous mobility research and early commercial deployments.",
  },
  {
    slug: "charlotte",
    name: "Charlotte",
    state: "NC",
    population: "874,579",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#0066ff",
    description: "Fast-growing financial hub actively investing in smart mobility infrastructure to manage rapid urban expansion.",
  },
  {
    slug: "salt-lake-city",
    name: "Salt Lake City",
    state: "UT",
    population: "199,723",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Mountain West hub with strong tech economy and proactive smart city planning for autonomous vehicle deployment.",
  },
  {
    slug: "tampa",
    name: "Tampa",
    state: "FL",
    population: "392,890",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing", "Zipline"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Florida's technology hub with active AV pilots and significant drone delivery activity across the Tampa Bay metro.",
  },
  {
    slug: "orlando",
    name: "Orlando",
    state: "FL",
    population: "307,573",
    avOperators: ["May Mobility", "Beep"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "active",
    accentColor: "#7b2fff",
    description: "Theme park capital with active autonomous shuttle deployments and significant autonomous infrastructure investment from tourism operators.",
  },
  {
    slug: "sacramento",
    name: "Sacramento",
    state: "CA",
    population: "524,943",
    avOperators: ["Waymo", "Nuro"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "California's capital city expanding AV operations as part of state-wide autonomous mobility initiatives.",
  },
  {
    slug: "detroit",
    name: "Detroit",
    state: "MI",
    population: "632,464",
    avOperators: ["Cruise", "Waymo", "May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 2,
    avActivity: "active",
    accentColor: "#ff9a00",
    description: "Motor City is at the forefront of AV development. GM's Cruise, Waymo, and May Mobility all operate here with strong OEM backing.",
  },
  {
    slug: "philadelphia",
    name: "Philadelphia",
    state: "PA",
    population: "1,576,251",
    avOperators: ["Waymo", "Aurora"],
    droneOperators: ["Zipline"],
    tier: 2,
    avActivity: "pilot",
    accentColor: "#0066ff",
    description: "Northeast corridor major city expanding AV pilots with dense urban infrastructure and high-volume transit connections.",
  },
  {
    slug: "columbus",
    name: "Columbus",
    state: "OH",
    population: "905,748",
    avOperators: ["May Mobility", "Nuro"],
    droneOperators: ["Wing"],
    tier: 2,
    avActivity: "active",
    accentColor: "#00d4ff",
    description: "Smart Columbus initiative leader with active May Mobility fixed-route deployments and a national AV testing corridor.",
  },

  // ── TIER 3 ────────────────────────────────────────────────────────────────
  {
    slug: "indianapolis",
    name: "Indianapolis",
    state: "IN",
    population: "887,642",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Racing capital investing in autonomous mobility infrastructure as part of smart city modernization initiatives.",
  },
  {
    slug: "jacksonville",
    name: "Jacksonville",
    state: "FL",
    population: "949,611",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Florida's largest city by area actively planning autonomous vehicle infrastructure for its sprawling geography.",
  },
  {
    slug: "san-antonio",
    name: "San Antonio",
    state: "TX",
    population: "1,434,625",
    avOperators: ["Nuro", "May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Texas's second-largest city with growing autonomous mobility interest driven by military and healthcare sector demand.",
  },
  {
    slug: "fort-worth",
    name: "Fort Worth",
    state: "TX",
    population: "935,508",
    avOperators: ["Aurora", "Nuro"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "DFW's western anchor city advancing smart mobility as part of the broader Dallas-Fort Worth AV corridor.",
  },
  {
    slug: "baltimore",
    name: "Baltimore",
    state: "MD",
    population: "585,708",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Mid-Atlantic port city developing autonomous infrastructure strategies alongside Washington DC metro expansion.",
  },
  {
    slug: "louisville",
    name: "Louisville",
    state: "KY",
    population: "633,045",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "UPS Flight Forward"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Major logistics hub with UPS and Amazon significant presence. Drone delivery infrastructure is a natural priority.",
  },
  {
    slug: "milwaukee",
    name: "Milwaukee",
    state: "WI",
    population: "577,222",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Great Lakes industrial city transitioning to smart infrastructure with autonomous transit planning underway.",
  },
  {
    slug: "kansas-city",
    name: "Kansas City",
    state: "MO",
    population: "508,090",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Central US logistics hub with smart city initiatives and growing interest in autonomous delivery and transit infrastructure.",
  },
  {
    slug: "oklahoma-city",
    name: "Oklahoma City",
    state: "OK",
    population: "681,054",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Oklahoma's capital actively modernizing transportation infrastructure with autonomous mobility in long-term plans.",
  },
  {
    slug: "tucson",
    name: "Tucson",
    state: "AZ",
    population: "542,629",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Arizona's second city benefiting from proximity to Phoenix's active AV market and University of Arizona research.",
  },
  {
    slug: "albuquerque",
    name: "Albuquerque",
    state: "NM",
    population: "564,559",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Southwest hub with Sandia National Labs and UNM driving autonomous technology research and early deployment planning.",
  },
  {
    slug: "fresno",
    name: "Fresno",
    state: "CA",
    population: "542,107",
    avOperators: ["Nuro"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Central Valley hub with Nuro delivery operations and growing autonomous infrastructure planning aligned with California state policy.",
  },
  {
    slug: "mesa",
    name: "Mesa",
    state: "AZ",
    population: "504,258",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#00ff88",
    description: "Adjacent to Phoenix's active Waymo service area, Mesa is one of the first suburban cities with regular autonomous vehicle operations.",
  },
  {
    slug: "colorado-springs",
    name: "Colorado Springs",
    state: "CO",
    population: "472,688",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Military and aerospace city planning autonomous infrastructure for its growing tech sector and military campus needs.",
  },
  {
    slug: "virginia-beach",
    name: "Virginia Beach",
    state: "VA",
    population: "459,470",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Hampton Roads military hub planning autonomous vehicle infrastructure to serve military bases and growing tech economy.",
  },
  {
    slug: "raleigh-durham",
    name: "Durham",
    state: "NC",
    population: "283,506",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Research Triangle tech hub with Duke University and top healthcare systems driving autonomous infrastructure demand.",
  },
  {
    slug: "richmond",
    name: "Richmond",
    state: "VA",
    population: "226,610",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Virginia's capital city integrating autonomous mobility into its smart city master plan and transit modernization.",
  },
  {
    slug: "st-louis",
    name: "St. Louis",
    state: "MO",
    population: "301,578",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Gateway city developing autonomous transportation strategies as part of its MetroLink transit corridor modernization.",
  },
  {
    slug: "cleveland",
    name: "Cleveland",
    state: "OH",
    population: "367,991",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Ohio's second city investing in smart infrastructure alongside Columbus as part of a statewide AV corridor strategy.",
  },
  {
    slug: "cincinnati",
    name: "Cincinnati",
    state: "OH",
    population: "309,317",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Amazon Air Hub home with significant drone delivery potential and growing smart city transportation investments.",
  },
  {
    slug: "madison",
    name: "Madison",
    state: "WI",
    population: "269,196",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "University of Wisconsin research city with strong autonomous vehicle research program and early smart city adoption.",
  },
  {
    slug: "boise",
    name: "Boise",
    state: "ID",
    population: "235,684",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Idaho's fastest-growing city planning autonomous infrastructure to manage rapid population growth and tech sector expansion.",
  },
  {
    slug: "scottsdale",
    name: "Scottsdale",
    state: "AZ",
    population: "241,361",
    avOperators: ["Waymo", "Cruise"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#7b2fff",
    description: "Within Waymo's Phoenix metro service area, Scottsdale has one of the highest concentrations of robotaxi operations per capita.",
  },
  {
    slug: "chandler",
    name: "Chandler",
    state: "AZ",
    population: "261,165",
    avOperators: ["Waymo"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#00d4ff",
    description: "Waymo's original home city where autonomous vehicles first operated commercially. Deep AV operational experience.",
  },
  {
    slug: "henderson",
    name: "Henderson",
    state: "NV",
    population: "320,189",
    avOperators: ["Zoox", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Las Vegas suburb with autonomous infrastructure planning aligned with Nevada's progressive AV regulation.",
  },
  {
    slug: "plano",
    name: "Plano",
    state: "TX",
    population: "285,494",
    avOperators: ["Nuro", "Aurora"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "DFW tech suburb with Toyota and other major AV-adjacent companies headquartered here, driving deployment activity.",
  },
  {
    slug: "el-paso",
    name: "El Paso",
    state: "TX",
    population: "678,815",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Border city planning smart infrastructure for its unique cross-border logistics environment and military presence.",
  },
  {
    slug: "new-orleans",
    name: "New Orleans",
    state: "LA",
    population: "383,997",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Historic city investing in autonomous infrastructure to modernize transit and manage its complex tourism-driven curb environment.",
  },
  {
    slug: "memphis",
    name: "Memphis",
    state: "TN",
    population: "633,104",
    avOperators: ["May Mobility"],
    droneOperators: ["FedEx", "Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "FedEx World Hub makes Memphis a natural drone delivery market. Autonomous last-mile logistics is a priority.",
  },
  {
    slug: "omaha",
    name: "Omaha",
    state: "NE",
    population: "486,051",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Midwestern hub with Union Pacific headquarters and growing logistics tech sector driving autonomous infrastructure planning.",
  },
  {
    slug: "hartford",
    name: "Hartford",
    state: "CT",
    population: "121,054",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Connecticut capital with strong insurance and healthcare sectors driving liability-focused autonomous infrastructure adoption.",
  },
  {
    slug: "providence",
    name: "Providence",
    state: "RI",
    population: "190,934",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Rhode Island capital with Brown University and RISD driving innovation in autonomous mobility research and deployment.",
  },
  {
    slug: "buffalo",
    name: "Buffalo",
    state: "NY",
    population: "278,349",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Rust Belt resurgence city integrating autonomous transit into infrastructure modernization as manufacturing transitions.",
  },
  {
    slug: "rochester",
    name: "Rochester",
    state: "NY",
    population: "211,328",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Photonics and imaging technology hub with University of Rochester driving AV sensor technology commercialization.",
  },
  {
    slug: "tulsa",
    name: "Tulsa",
    state: "OK",
    population: "413,066",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Oklahoma's second city with growing remote work economy and smart infrastructure investments attracting tech companies.",
  },
  {
    slug: "oakland",
    name: "Oakland",
    state: "CA",
    population: "440,646",
    avOperators: ["Waymo", "Cruise"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#00ff88",
    description: "Part of the SF Bay Area AV ecosystem with Waymo and Cruise operations extending across the Bay.",
  },
  {
    slug: "long-beach",
    name: "Long Beach",
    state: "CA",
    population: "466,742",
    avOperators: ["Nuro", "Waymo"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Major port city with significant autonomous freight and last-mile delivery potential tied to the Port of Long Beach.",
  },
  {
    slug: "anaheim",
    name: "Anaheim",
    state: "CA",
    population: "346,824",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Disneyland's home city with high-density tourism driving autonomous curb management demand at hotels and attractions.",
  },
  {
    slug: "riverside",
    name: "Riverside",
    state: "CA",
    population: "314,998",
    avOperators: ["Waymo"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Inland Empire logistics hub with Amazon and major warehouse operations driving autonomous delivery infrastructure demand.",
  },
  {
    slug: "stockton",
    name: "Stockton",
    state: "CA",
    population: "320,804",
    avOperators: ["Nuro"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Central Valley logistics city with growing autonomous delivery presence connected to Bay Area tech ecosystem.",
  },
  {
    slug: "wichita",
    name: "Wichita",
    state: "KS",
    population: "389,938",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Aviation capital with strong aerospace industry driving interest in UAM and autonomous air mobility infrastructure.",
  },
  {
    slug: "greensboro",
    name: "Greensboro",
    state: "NC",
    population: "296,710",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Piedmont Triad city investing in smart infrastructure as part of the broader Research Triangle autonomous mobility ecosystem.",
  },
  {
    slug: "lincoln",
    name: "Lincoln",
    state: "NE",
    population: "291,082",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "University of Nebraska hub with growing tech sector and smart city ambitions aligned with Midwest AV corridor planning.",
  },
  {
    slug: "st-paul",
    name: "St. Paul",
    state: "MN",
    population: "311,527",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#7b2fff",
    description: "Twin Cities partner city sharing Minneapolis's autonomous mobility infrastructure strategy and cold-weather AV testing.",
  },
  {
    slug: "norfolk",
    name: "Norfolk",
    state: "VA",
    population: "238,005",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Naval Station Norfolk drives significant autonomous vehicle and drone infrastructure demand for military logistics.",
  },
  {
    slug: "fort-lauderdale",
    name: "Fort Lauderdale",
    state: "FL",
    population: "182,595",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "South Florida hub with Broward County infrastructure investments and proximity to Miami's active AV ecosystem.",
  },
  {
    slug: "honolulu",
    name: "Honolulu",
    state: "HI",
    population: "350,964",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Island geography creates unique drone delivery economics. Autonomous last-mile delivery is a natural fit for Honolulu.",
  },
  {
    slug: "spokane",
    name: "Spokane",
    state: "WA",
    population: "228,989",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Eastern Washington hub expanding smart infrastructure as part of the state's broader autonomous mobility strategy.",
  },
  {
    slug: "tacoma",
    name: "Tacoma",
    state: "WA",
    population: "219,346",
    avOperators: ["Amazon", "Waymo"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Port of Tacoma proximity makes this city a natural autonomous freight and last-mile logistics hub.",
  },
  {
    slug: "birmingham",
    name: "Birmingham",
    state: "AL",
    population: "212,237",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Alabama's largest city with major healthcare sector driving medical drone delivery and autonomous patient transport interest.",
  },
  {
    slug: "tempe",
    name: "Tempe",
    state: "AZ",
    population: "195,805",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#00ff88",
    description: "Arizona State University home with active Waymo robotaxi service and a dense urban core ideal for autonomous vehicle infrastructure.",
  },
  {
    slug: "aurora-co",
    name: "Aurora",
    state: "CO",
    population: "366,623",
    avOperators: ["Aurora", "Waymo"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#0066ff",
    description: "Denver suburb with Aurora Innovation headquarters nearby and active AV freight corridor testing on Interstate 70.",
  },
  {
    slug: "corpus-christi",
    name: "Corpus Christi",
    state: "TX",
    population: "316,381",
    avOperators: ["May Mobility"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "Texas Gulf Coast city with petrochemical and military sectors driving autonomous infrastructure investment.",
  },
  {
    slug: "lexington",
    name: "Lexington",
    state: "KY",
    population: "322,570",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Kentucky's second city with University of Kentucky research and Toyota manufacturing presence driving AV interest.",
  },
  {
    slug: "anchorage",
    name: "Anchorage",
    state: "AK",
    population: "291,247",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing", "Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Alaska's largest city with extreme weather presenting unique AV and drone delivery opportunities for remote area logistics.",
  },
  {
    slug: "winston-salem",
    name: "Winston-Salem",
    state: "NC",
    population: "249,545",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Wake Forest Innovation Quarter anchors this Piedmont city's smart technology ambitions including autonomous mobility.",
  },
  {
    slug: "garland",
    name: "Garland",
    state: "TX",
    population: "246,018",
    avOperators: ["Aurora", "Nuro"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "DFW suburb with significant warehouse and distribution infrastructure driving autonomous last-mile delivery demand.",
  },
  {
    slug: "lubbock",
    name: "Lubbock",
    state: "TX",
    population: "255,885",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "West Texas hub with Texas Tech University driving research into autonomous agriculture and urban delivery systems.",
  },
  {
    slug: "laredo",
    name: "Laredo",
    state: "TX",
    population: "255,205",
    avOperators: ["Aurora"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Largest US-Mexico inland port with autonomous freight trucks as a natural infrastructure priority for cross-border logistics.",
  },
  {
    slug: "fort-wayne",
    name: "Fort Wayne",
    state: "IN",
    population: "270,402",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Indiana manufacturing hub investing in autonomous infrastructure to modernize logistics and workforce mobility.",
  },
  {
    slug: "jersey-city",
    name: "Jersey City",
    state: "NJ",
    population: "292,449",
    avOperators: ["Waymo", "Zoox"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "New York metro satellite city with dense urban core and significant AV expansion interest as Waymo extends NYC operations.",
  },
  {
    slug: "gilbert",
    name: "Gilbert",
    state: "AZ",
    population: "267,918",
    avOperators: ["Waymo"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#ff9a00",
    description: "Suburban Phoenix city within Waymo's active service area and one of the fastest-growing cities in America.",
  },
  {
    slug: "irvine",
    name: "Irvine",
    state: "CA",
    population: "307,670",
    avOperators: ["Waymo", "Zoox"],
    droneOperators: ["Wing", "Amazon Prime Air"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#7b2fff",
    description: "Planned city with wide arterials and tech-sector density. UCI and major tech campuses drive AV infrastructure demand.",
  },
  {
    slug: "fremont",
    name: "Fremont",
    state: "CA",
    population: "230,504",
    avOperators: ["Waymo", "Nuro"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "pilot",
    accentColor: "#00d4ff",
    description: "Home to Tesla's Fremont factory and deep EV manufacturing roots. AV and smart mobility infrastructure is a natural fit.",
  },
  {
    slug: "glendale",
    name: "Glendale",
    state: "AZ",
    population: "252,381",
    avOperators: ["Waymo", "May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "active",
    accentColor: "#00ff88",
    description: "West Phoenix suburb within Waymo's Phoenix service zone with significant sports and entertainment venue curb management needs.",
  },
  {
    slug: "aurora-il",
    name: "Aurora",
    state: "IL",
    population: "197,899",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#0066ff",
    description: "Chicago's western suburb investing in autonomous transit as part of the broader Chicago metro AV expansion.",
  },
  {
    slug: "chula-vista",
    name: "Chula Vista",
    state: "CA",
    population: "275,487",
    avOperators: ["Waymo"],
    droneOperators: ["Amazon Prime Air"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#ff9a00",
    description: "San Diego's largest suburb and one of California's fastest-growing cities, planning autonomous mobility as infrastructure matures.",
  },
  {
    slug: "henderson-nv",
    name: "North Las Vegas",
    state: "NV",
    population: "262,527",
    avOperators: ["Zoox"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#7b2fff",
    description: "Rapidly growing Nevada city adjacent to Las Vegas with growing logistics and distribution infrastructure driving AV demand.",
  },
  {
    slug: "sioux-falls",
    name: "Sioux Falls",
    state: "SD",
    population: "192,517",
    avOperators: ["May Mobility"],
    droneOperators: ["Wing"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00d4ff",
    description: "Upper Midwest financial hub and one of America's fastest-growing small cities actively pursuing smart infrastructure investments.",
  },
  {
    slug: "baton-rouge",
    name: "Baton Rouge",
    state: "LA",
    population: "227,470",
    avOperators: ["May Mobility"],
    droneOperators: ["Zipline"],
    tier: 3,
    avActivity: "planning",
    accentColor: "#00ff88",
    description: "Louisiana capital with major petrochemical, healthcare, and university sectors driving autonomous infrastructure interest.",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
